In [1]:
from easybullet.pose import SO3

In [2]:
rot = SO3.identity()

In [3]:
rot.exp()

array([0., 0., 0.])

In [7]:
SO3.from_euler("xyz", [1,0,0])

In [6]:
(rot @ rot.inverse()).xyzw

array([0., 0., 0., 1.])

In [6]:
rot.inverse()@rot

SO3(xyzw=[0. 0. 0. 1.])

In [4]:
rot.wxyz

array([-0.8953247 , -0.35146215, -0.23285017, -0.14369703])

In [5]:
rot.inverse()

SO3(xyzw=[ 0.35146  0.23285  0.1437  -0.89532])

In [1]:
import numpy as np

In [27]:
from __future__ import annotations
from scipy.spatial.transform import Rotation
from dataclasses import dataclass
import numpy as np
from typing import *
from typing_extensions import override

class SO3(Rotation):
    def __init__(self, xyzw):
        super().__init__(quat=xyzw)
    
    @property
    def xyzw(self): return self.as_quat()
    @property
    def wxyz(self): return np.roll(self.as_quat(), 1)
    def __repr__(self) -> str:
        xyzw = np.round(self.xyzw, 5)
        return f"{self.__class__.__name__}(wxyz={xyzw})"
    
    @classmethod
    def from_rotation_class(cls, rot:Rotation):
        return cls(rot.as_quat())
    @classmethod
    def from_wxyz(cls, wxyz):
        return cls(np.roll(wxyz, -1))
    @override
    @classmethod
    def random(cls):
        return cls.from_rotation_class(Rotation.random())
    @override
    @classmethod
    def identity(cls):
        return cls([0,0,0,1])
    @override
    @classmethod
    def from_euler(cls, seq: str, angles: Sequence[float]):
        """{‘X’, ‘Y’, ‘Z’} for intrinsic rotations, or {‘x’, ‘y’, ‘z’} for extrinsic rotations"""
        return cls.from_rotation_class(Rotation.from_euler(seq, angles))
    @override
    @classmethod
    def from_matrix(cls, mat:np.ndarray):
        return cls.from_rotation_class(Rotation.from_matrix(mat))
    @override
    def inverse(self):
        return SO3.from_rotation_class(self.inv())
    @override
    def apply(self, target: np.ndarray) -> np.ndarray:
        return super().apply(target)
    def multiply(self, target: SO3):
        return SO3.from_rotation_class(self * target)
    def __matmul__(self, target: Union[SO3, np.ndarray]):
        if isinstance(target, SO3):
            return self.multiply(target)
        elif isinstance(target, np.ndarray):
            return self.apply(target)
        raise ValueError

In [28]:
rot = SO3.random()

In [32]:
rot.__dir__()

['__module__',
 '__init__',
 'xyzw',
 'wxyz',
 '__repr__',
 'from_rotation_class',
 'from_wxyz',
 'random',
 'identity',
 'from_euler',
 'from_matrix',
 'inverse',
 'apply',
 'multiply',
 '__matmul__',
 '__dict__',
 '__weakref__',
 '__doc__',
 '__mul__',
 '__rmul__',
 '__len__',
 '__getitem__',
 '__setitem__',
 '__delitem__',
 '__new__',
 '__getstate__',
 '__setstate__',
 'from_quat',
 'from_rotvec',
 'from_mrp',
 'as_quat',
 'as_matrix',
 'as_rotvec',
 'as_euler',
 'as_mrp',
 'concatenate',
 'inv',
 'magnitude',
 'mean',
 'reduce',
 'create_group',
 'align_vectors',
 '__reduce_cython__',
 '__setstate_cython__',
 'single',
 '__hash__',
 '__str__',
 '__getattribute__',
 '__setattr__',
 '__delattr__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__reduce_ex__',
 '__reduce__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__']

In [34]:
rot.inv()

TypeError: __init__() got an unexpected keyword argument 'copy'

In [30]:
rot.__mul__(rot)

TypeError: __init__() got an unexpected keyword argument 'normalize'

In [17]:
isinstance(rot, Rotation)

True

In [18]:
rot * rot

TypeError: __init__() got an unexpected keyword argument 'normalize'

In [12]:
rot1 = Rotation(rot.xyzw)

In [14]:
rot1.__dict__

AttributeError: 'scipy.spatial.transform._rotation.Rotation' object has no attribute '__dict__'